name: Deploy to PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PYTHONANYWHERE_SSH_PRIVATE_KEY }}

      - name: Deploy to PythonAnywhere
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PYTHONANYWHERE_USERNAME }}@${{ secrets.PYTHONANYWHERE_HOST }} "cd ~/wedding-website && git pull && source venv/bin/activate && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && touch /var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}.pythonanywhere.com_wsgi.py"
